### PR TITLE
Localstorage add client id key

### LINKED ISSUE #16: [v2.0] localstorage cache key should probably be client dependant
the localstorage key should have the client id in it, as the cookie storage key (the cookie name) does.

I think it should be possible for more than one client to operate on the same brower origin.

### PR DESCRIPTION
**Pull request by erikfried**
Alternative solution for #17 and closes #16 

ping @joawan @thogra

### CODE REVIEW

**Comment by erikfried** [comment]
Verified this works :ok:  on a testpage i have, using multiple clients.

**Comment by joawan** [comment]
#17 or #18?

**Comment by erikfried** [comment]
@joawan I guess it´s up to the Owner to decide ;-)

I believe both are valid fixes for the issue, but I would favour this one because it harmonises the apis of the `cookie` and `localstorage` modules a bit. And that might be a Good Thing :tm:

**Comment by danielbentes** [comment]
Harmonising APIs sounds like a good thing :)

**Comment by thogra** [comment]
:+1: for this (#18)

**Comment by joawan** [comment]
LGMT!

**Pull request merged**
