### PR TITLE
SDK release versioning

### PR DESCRIPTION
**Pull request by thogra**
## How do I even release
I'm operating under a couple of assumptions (correct me if I'm wrong)
 - The `/dist/` directory shouldn't even be checked in (note: added `dist/` to `.gitignore`)
 - We should attach the "built" files, as a `zip`, to the Github release
 - "dist" files should contain the version number in the file name as well as in the code
 - There's no need for releasing to NPM

It's entirely possible to do this manually. I'm sure we can automate it too (soon, in this PR), maybe even do it with [Travis](https://travis-ci.org/) if we want to do like that.

@joawan @erikfried

### CODE REVIEW

**Comment by thogra** [comment]
I've added some automation to creating releases, via the `release-it` grunt task. The idea is to:
 1. Bump the version number to be released in `package.json`
 2. `$> grunt release`
 3. Upload the `dist/spid-sdk-X.Y.Z.zip` to the GitHub release via the UI (couldn't automate this part easily, because https://github.com/webpro/release-it/issues/32)
 4. Profit

**Comment by erikfried** [comment]
Why does the version number need to be in the artifact name? (Honest question)

**Comment by erikfried** [comment]
FWIW: We would appreciate (and use) releases to npm

**Comment by thogra** [comment]
The reasoning was to that we could keep serving the SDK files (from ... wherever that's being done right now) as simple as possible.

**Pull request merged**
